name: ssm
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.4=py39hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2021.10.8=py39hf3d152e_2
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cmake=3.19.6=h973ab73_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - commonmark=0.9.1=pyhd3eb1b0_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.2=py39h06a4308_1
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.9.1=py39h06a4308_0
  - ipython=8.1.1=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py39h06a4308_7
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libcurl=7.80.0=h0b77cf5_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=3_h893e4fe_netlib
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.46.0=hce63b2e_0
  - libopenblas=0.3.17=hf726d26_1
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - llvmlite=0.38.0=py39h4ff587b_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.5.1=py39h06a4308_1
  - matplotlib-base=3.5.1=py39ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2020.2=256
  - mkl-include=2022.0.1=h06a4308_117
  - mkl-service=2.3.0=py39he8ac12f_0
  - mkl_fft=1.3.0=py39h54f3939_0
  - mkl_random=1.0.2=py39h63df603_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.3.0=py39h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - ninja=1.10.2=py39hd09550d_3
  - notebook=6.4.8=py39h06a4308_0
  - numba=0.55.1=py39h51133e4_0
  - numexpr=2.7.3=py39hb2eb853_0
  - numpy=1.19.2=py39h89c1606_0
  - numpy-base=1.19.2=py39h2ae0177_0
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py39h295c915_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=21.2.4=py39h06a4308_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.11=h12debd9_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py39h7f8727e_1
  - pyzmq=22.3.0=py39h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - qtpy=1.11.2=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - resampy=0.2.2=py_0
  - rhash=1.4.1=h3c74f83_1
  - rich=10.16.2=pyhd3eb1b0_0
  - scipy=1.5.3=py39hf3f25e7_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=hd09550d_0
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.63.0=pyhd3eb1b0_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - anytree==2.8.0
    - async-timeout==4.0.2
    - cachetools==5.2.0
    - click==8.1.3
    - crccheck==1.1
    - einops==0.4.1
    - et-xmlfile==1.1.0
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - h5py==3.7.0
    - imageio==2.22.0
    - ishneholterlib==2020.5.29
    - joblib==1.2.0
    - markdown==3.4.1
    - mlxtend==0.21.0
    - multidict==6.0.2
    - networkx==2.8.6
    - oauthlib==3.2.1
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pytorch-lightning==1.7.7
    - pywavelets==1.4.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - sklearn==0.0
    - soundfile==0.11.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tifffile==2022.8.12
    - torchmetrics==0.9.3
    - torchvision==0.11.3
    - werkzeug==2.2.2
    - wfdb==4.0.0
    - wget==3.2
    - yarl==1.8.1

